### ISSUE TITLE
I love hyper-rose-pine 

### ISSUE THREAD

**Issue by markozxuu** [rose-pine/hyper#1]
Thanks ! The look of my terminal as a code editor look amazing :D 🚀 

<img width="1274" alt="Screen Shot 2020-03-15 at 12 23 50" src="https://user-images.githubusercontent.com/16585386/76707795-e5e10880-66b7-11ea-856a-23814946218d.png">

**Comment by fvrests** [comment]
Thanks so much!!! I'm so happy one of my first projects is making a difference. I happen to have that setup too 🥳 Always open to suggestions here if you need anything ✨
