### ISSUE TITLE
Dawn & Moon

### ISSUE THREAD

**Issue by ng-hai** [rose-pine/hyper#6]
I want to make Dawn & Moon theme available for Hyper. Should I create a repo for each theme, or contribute to this repo to make it configurable via Hyper's settings?

**Comment by mvllow** [comment]
Honestly whatever you think is best. Most of our terminal themes are a simple file, eg. `rose-pine.yaml` so that's easy to have in a single repo but because this is on npm we may want a monorepo? I don't have much experience with those. If separate repos are easiest then that's fine too 😌 

Thanks for wanting to contribute!

(@fvrests is the maintainer of this one so maybe they have something to add)

**Comment by ng-hai** [comment]
Yeah, waiting for @fvrests idea. Suddenly know Rosé Pine, and now I want everything uses Rosé Pine palette, even my website too 😄

**Comment by ng-hai** [comment]
My first draft

https://user-images.githubusercontent.com/19520278/117956312-20d5df00-b343-11eb-959d-856ebbde7544.mov

**Comment by mvllow** [comment]
Love it! I didn't even know switching variants like that was possible 😅

**Comment by ng-hai** [comment]
Actually I want to switch variants automatically based on System Preference > Appearance, even try to create a plugin for that, but got no luck because of Hyper's architecture.

**Comment by fvrests** [comment]
Sorry for the delay & thanks for your patience as my non-tech job is taking a lot of my bandwidth at the moment... Your additions look wonderful & I'm so glad you are loving Rosé Pine 🥰 Thank you so much for making this issue & contributing - the view menu item for switching themes is so clean! 

If you are willing to contribute your changes as a PR & if it's possible to add it all to the main repo, I would absolutely accept the PR and credit you for the changes. 

If not, I would be happy to link out to your repos or help build a monorepo if you think that's the best way to do it :) I admit I'm not the most experienced with how to best structure the repo for theme switching, so let me know what you think.

**Comment by ng-hai** [comment]
Thanks for your kind words. I have managed to do this out. The plugin now can react to Appearance Settings, in short it supports dark mode. I also add Rose Pine logo to each tab title.

But there is one issue, this only works with Hyper's canary release version. So I'm not sure it's a good idea to replace your current package.

https://user-images.githubusercontent.com/19520278/118404267-750ef500-b69c-11eb-92ae-8329ae89e2e7.mov

**Comment by ng-hai** [comment]
Please take a look, or test it out 😄

https://github.com/ng-hai/hyper-rose-pine

**Comment by ng-hai** [comment]
Hey, I have a good news, my fork is now compatible with the current original version. Tested on production by adding this line into your config.

```js
plugins: [
    // another plugins...
    "hyper-rose-pine@git+https://github.com/ng-hai/hyper-rose-pine",
  ]
```

Then go to menu `Plugins > Update` or `Cmd+Shift+U` to make Hyper install new code.

**Comment by fvrests** [comment]
<img width="580" alt="Screen Shot of Hyper terminal with Rose Pine theme" src="https://user-images.githubusercontent.com/47515065/118882231-94369e00-b8b9-11eb-982c-756f6341b8c0.png">

@ng-hai Oh no, just installed and it looks like this to me! The syntax theme doesn't look like it applied as well as the problem with the large icon. I had @mvllow try it on his and it looks similar to mine. I'll try to help take a look at it later when I'm done with work for the day, but let us know if there's anything else you need to help figure it out. ):

**Comment by mvllow** [comment]
Went ahead and added moon/dawn to the original base. Variant can be set via an option in `~/.hyper.js`. We will gladly feature a hyper plugin that allows switching variants based on OS theme etc.

**Comment by ng-hai** [comment]
It's weird because I had fixed that bug before opening the PR :(
