### ISSUE TITLE
Plugin error when decorating decorateConfig

### ISSUE THREAD

**Issue by voidgraphics** [rose-pine/hyper#8]
Hello! Thank you for the cool theme! I get this error and the theme does not load:

![Screenshot 2021-06-29 at 09 44 09](https://user-images.githubusercontent.com/9298484/123757816-a0e9e100-d8be-11eb-8c0c-0ceb13a9f191.png)

Is this a known issue? Using version 2.1.0

Thank you

**Comment by mvllow** [comment]
Oh no! I'll have to see if I can reproduce this issue. In the meantime, you can use `plugins: ["hyper-rose-pine#2.0.1"]` or maybe check out this [community version](https://github.com/ng-hai/hyper-rose-pine-next).

Thanks for the report 🥰
